// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOeCHSFKJq-wdllh8flJJb8bo8fTpEYE0',
    appId: '1:924143723405:web:100373785c8dd33e7a13c4',
    messagingSenderId: '924143723405',
    projectId: 'fir-crud-f336f',
    authDomain: 'fir-crud-f336f.firebaseapp.com',
    storageBucket: 'fir-crud-f336f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3NMi4fqMsyKI8-FhsEuIM9FnCOk0voQA',
    appId: '1:924143723405:android:e4144bccf9cf913f7a13c4',
    messagingSenderId: '924143723405',
    projectId: 'fir-crud-f336f',
    storageBucket: 'fir-crud-f336f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqG9fPyiJ2izPVBtuV6yX6udWN4D4Ojeo',
    appId: '1:924143723405:ios:8ef9761931a29f7e7a13c4',
    messagingSenderId: '924143723405',
    projectId: 'fir-crud-f336f',
    storageBucket: 'fir-crud-f336f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqG9fPyiJ2izPVBtuV6yX6udWN4D4Ojeo',
    appId: '1:924143723405:ios:77e446f22c7298797a13c4',
    messagingSenderId: '924143723405',
    projectId: 'fir-crud-f336f',
    storageBucket: 'fir-crud-f336f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
